workReport/Models/user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int usrId { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> post { get; set; }
        public string contractDate { get; set; }
        public Nullable<int> monthlySalary { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public string bankName { get; set; }
        public string branch { get; set; }
        public string acnumber { get; set; }
        public Nullable<int> lastMonthAmount { get; set; }
        public string enteredDate { get; set; }
        public string passencryp { get; set; }
        public string passkey { get; set; }
    }
}

workReport/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using workReport.Models;

namespace workReport.Controllers
{
    public class usersController : SessionCheckController
    {
        private workReportEntities db = new workReportEntities();

        // GET: users
        public ActionResult Index()
        {
            return View(db.user.ToList());
        }

        public ActionResult ChangePassword()
        {

            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(FormCollection fc)
        {
            string oldpassword = fc["oldPassword"].ToString().Trim();
            string newpassword = fc["newOldPassword"].ToString().Trim();
            int isUserId = Convert.ToInt32(Session["userId"]);
            user isUser = db.user.Find(isUserId);
            string encyKey = isUser.passkey;
            string encOldPassword = CommonController.Encrypt(oldpassword,encyKey);

           
            while (isUser.passencryp==encOldPassword)
            {
                isUser.userPassword = newpassword;
                 string newpasskey = CommonController.RandomString(15);
                isUser.passkey = newpasskey;
                isUser.passencryp = CommonController.Encrypt(newpassword, newpasskey);
                db.Entry(isUser).State = EntityState.Modified;
                db.SaveChanges();
                Session.Abandon();
                FormsAuthentication.SignOut();
                return Redirect("/Login/SignIn");

            }
            ViewBag.message = "Something Went Wrong!!";
            return View();
        }
        //// GET: users/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    user user = db.user.Find(id);
        //    if (user == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(user);
        //}

        // GET: users/Create
     

        [HttpPost]
        public JsonResult CheckUsername(string username)
        {
          
            bool isValid = db.user.ToList().Exists(p => p.userName.Equals(username, StringComparison.CurrentCultureIgnoreCase));
                return Json(isValid);
        }



        // POST: users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
       

        // GET: users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = db.user.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "usrId,userName,userPassword,firstName,lastName,post,contractDate,monthlySalary,totalAmount,bankName,branch,acnumber")] user user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        
      


        // GET: users/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    user user = db.user.Find(id);
        //    if (user == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(user);
        //}

        //// POST: users/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    user user = db.user.Find(id);
        //    db.user.Remove(user);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

workReport/Views/users/ChangePassword.cshtml
<div class="container" style="padding: 50px 0;">
    <div class="row" style="margin-top:20px">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            @using (Html.BeginForm("ChangePassword", "users", FormMethod.Post))
            {
                var msg = @ViewBag.message;
                <fieldset>
                    <h2>Change Password</h2>
                    <hr class="colorgraph">
                    <div class="form-group">
                        <input type="password" name="oldPassword" id="oldPassword" class="form-control input-lg" placeholder="Old Password" required />
                    </div>
                    <div class="form-group">
                        <input type="password" name="newOldPassword" id="newOldPassword" class="form-control input-lg" placeholder="New Password" required />
                    </div>
                    @*<span class="button-checkbox">
                        <button type="button" class="btn" data-color="info">Remember Me</button>
                        <input type="checkbox" name="remember_me" id="remember_me" checked="checked" class="hidden">


                        <a href="~/users/ForgotPassword" class="btn btn-link pull-right">Forgot Password?</a>



                    </span>*@
                    <hr class="colorgraph">
                   
                        <div class="form-group">
                            <input type="submit" class="btn btn-lg btn-success btn-block" value="Change Password">
                        </div>

                       
                   

                    <div class="row">
                        <h3>@msg</h3>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

workReport/Views/users/Create.cshtml
@*@model workReport.Models.user

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", @onchange = "CheckAvailability()",@onkeyup="ClearMessage()" } })
            @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
        </div>
    </div>
    <span id="message"></span>
    <div class="form-group">
        @Html.LabelFor(model => model.userPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.userPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.userPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.post, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("isPost", null, "--Select Post--", htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.contractDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.contractDate, new { htmlAttributes = new { @class = "form-control", placeholder = "2076-07-29" } })
            @Html.ValidationMessageFor(model => model.contractDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.monthlySalary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.monthlySalary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.monthlySalary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.totalAmount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.totalAmount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.totalAmount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.lastMonthAmount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.lastMonthAmount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lastMonthAmount, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.bankName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.bankName, new { htmlAttributes = new { @class = "form-control", placeholder = "Everest Bank Ltd." } })
            @Html.ValidationMessageFor(model => model.bankName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.branch, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.branch, new { htmlAttributes = new { @class = "form-control", placeholder = "New Baneshwor, Kathmandu" } })
            @Html.ValidationMessageFor(model => model.branch, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.acnumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.acnumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.acnumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" onclick="SubmitCheck()" />
        </div>
    </div>
</div>
}




<script type="text/javascript">
            function CheckAvailability() {
                var username = $("#userName").val();
                $.ajax({
                type: "POST",
                    url: "/users/CheckUsername",
                    data: '{username: "' + username + '" }',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (response) {
                        var message = $("#message");
                        message.html(null);
                        if (response) {
                           
                            message.css("color", "red");
                            message.html("username already exists!!");
                        }
                        else {
                //Email not available.
               

                            message.html = null;
                            //message.css("color", "green");
                            //message.html("Email is available");
                        }
                    }
                });
            };

            function ClearMessage() {
                $("#message").html("");
    };


    function SubmitCheck() {
        if (message.html == null) {
            alert("validation failed false");
          
            return false;
        }
        return true;
    };

    //$(document).ready(function () {
    //    $('input[type="submit"]').attr('disabled', 'disabled');
    //    $('input[type="text"]').change(function () {
    //        if ($(this).val != '') {
    //            $('input[type="submit"]').removeAttr('disabled');
    //        }
    //    });
    //});

    </script>*@

workReport/Views/users/ForgotPassword.cshtml
 
  
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/formdesign.css" rel="stylesheet" />
    <link href="~/Content/Login.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/Login.css">


    <div class="container" style="padding: 50px 0;">
        <div class="row" style="margin-top:20px">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                @using (Html.BeginForm("UpdatePassword", "users", FormMethod.Post))
                {
                    var msg = @ViewBag.message;
                <fieldset>
                    <h2>Reset Password</h2>
                    <hr class="colorgraph">
                    <div class="form-group">
                        <input type="text" name="username" id="username1" class="form-control input-lg" placeholder="Username" required />
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" id="password" class="form-control input-lg" placeholder="New Password" required />
                    </div>
                    <div class="form-group">
                        <input type="password" name="password1" id="password1" class="form-control input-lg" placeholder="Re-enter New Password"  required />
                    </div>
                    
                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <input type="submit" class="btn btn-lg btn-success btn-block" value="Submit">
                        </div>

                       
                    </div>

                    <div class="row">
                        <h3>@msg</h3>
                    </div>
                </fieldset>
                }
            </div>
        </div>
    </div>


 
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script >
    $("#username1").change(function () {
        debugger;
        var username = $("#username1").val();
        $.ajax({
            type: "POST",
            url: "/users/CheckUsername",
            data: '{username: "' + username + '" }',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                var message = $("#message");
                message.html(null);
                if (response) {

                    message.css("color", "green");

                }
                else {

                    message.css("color", "red");
                    //message.html = null;
                    ////message.css("color", "green");
                    ////message.html("Email is available");
                }
            }
        });
    });

    $("#password1").change(function () {
        var message = $("#message");
        var password = $("#password").val();
        var password1 = $("#password1").val();
        if (password == password1) {
            password1.css("color", "green");
        }
        else {
            password1.css("color", "red");
            message.html("password donot match!")
        }
    });

    </script>